### ISSUE TITLE
GitHub Actions 编译问题

### ISSUE THREAD

**Issue by google-mirror** [Xpsoted/action_build_twrp_device_tree#3]
[build] Unhandled exception. System.IO.IOException: No space left on device : '/home/runner/runners/2.290.1/_diag/Worker_20220419-1002

**Comment by Xpsoted** [comment]
这是硬盘内存满了

**Comment by Xpsoted** [comment]
写一个精简脚本

**Comment by google-mirror** [comment]
> 这是硬盘内存满了

你能跑完编译?这边发现repo sync这一步都同步不完, 已经用了精简版的manifest了

**Comment by Xpsoted** [comment]
精简php等组件试试，有yhml脚本在github上面

**Comment by google-mirror** [comment]
> 精简php等组件试试，有yhml脚本在github上面

应该不行, 我在本地跑, 占用了42G

**Comment by google-mirror** [comment]
> 精简php等组件试试，有yhml脚本在github上面

应该不行, 我在本地跑, 占用了42G
